import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

// 通过 WebView2 调试端口检验真实桌面命令；只替代文件选择器返回值，不替代 GIS 或生成后端。
const [endpoint, outputDirectory, workspace] = process.argv.slice(2);
await fs.mkdir(outputDirectory, { recursive: true });
// 调试端口可能先暴露 about:blank，等待工作台文档就绪后再访问存储与命令。
let target;
for (let attempt = 0; attempt < 60; attempt++) {
  const targets = await (await fetch(`${endpoint}/json`)).json();
  target = targets.find(item => item.type === 'page' && item.url.includes('tauri'));
  if (target) break;
  await new Promise(resolve => setTimeout(resolve, 250));
}
assert(target?.webSocketDebuggerUrl, '未找到桌面 WebView2 页面');
const socket = new WebSocket(target.webSocketDebuggerUrl);
await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; });
let sequence = 0;
const pending = new Map();
const browserErrors = [];
socket.onclose = event => { for (const handler of pending.values()) handler.reject(new Error(`WebView2 调试连接关闭：${event.code} ${event.reason}`)); pending.clear(); };
socket.onmessage = event => {
  const message = JSON.parse(event.data);
  if (message.id) {
    const handler = pending.get(message.id); pending.delete(message.id);
    if (message.error) handler.reject(new Error(JSON.stringify(message.error))); else handler.resolve(message.result);
  } else if (message.method === 'Runtime.exceptionThrown') browserErrors.push(message.params.exceptionDetails.text + ':' + (message.params.exceptionDetails.exception?.description ?? ''));
  else if (message.method === 'Runtime.consoleAPICalled' && message.params.type === 'error') browserErrors.push(message.params.args.map(item => item.description ?? item.value ?? '').join(' '));
  else if (message.method === 'Log.entryAdded' && message.params.entry.level === 'error') browserErrors.push(message.params.entry.text);
};
const command = (method, params = {}) => new Promise((resolve, reject) => {
  const id = ++sequence;
  const timer = setTimeout(() => { pending.delete(id); reject(new Error(`CDP 命令超时：${method}`)); }, 30000);
  pending.set(id, { resolve: value => { clearTimeout(timer); resolve(value); }, reject: error => { clearTimeout(timer); reject(error); } }); socket.send(JSON.stringify({ id, method, params }));
});
const evaluate = async expression => {
  const result = await command('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true });
  if (result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description ?? result.exceptionDetails.exception?.value ?? result.exceptionDetails.text);
  return result.result.value;
};
const waitFor = async (expression, seconds = 30) => {
  const limit = Date.now() + seconds * 1000;
  while (Date.now() < limit) { if (await evaluate(expression)) return; await new Promise(resolve => setTimeout(resolve, 150)); }
  throw new Error(`等待超时：${expression}\n${await evaluate('document.body.innerText')}`);
};
const invoke = (name, args = {}) => evaluate(`window.__TAURI_INTERNALS__.invoke(${JSON.stringify(name)},${JSON.stringify(args)})`);
const click = selector => evaluate(`(()=>{const button=document.querySelector(${JSON.stringify(selector)});if(!button)throw new Error('找不到按钮');button.click();})()`);
const clickText = text => evaluate(`(()=>{const button=[...document.querySelectorAll('button')].find(item=>item.innerText.trim()===${JSON.stringify(text)});if(!button)throw new Error('找不到按钮 '+${JSON.stringify(text)});button.click();})()`);
const queueDialog = (type, file) => evaluate(`window.__ROAD_WORKBENCH__.dialogs.${type}.push(${JSON.stringify(file)})`);
const screenshot = async name => { const result = await command('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false }); await fs.writeFile(path.join(outputDirectory, name), Buffer.from(result.data, 'base64')); };
let originalLayout;
const checks = [];
const check = (name, details) => checks.push({ name, passed: true, details });
try {
  await command('Runtime.enable'); await command('Page.enable'); await command('Log.enable');
  originalLayout=await evaluate('localStorage.getItem("road-workbench-layout")');
  await evaluate('localStorage.removeItem("road-workbench-layout")');
  await command('Page.reload');
  await waitFor('Boolean(window.__TAURI_INTERNALS__ && window.__ROAD_WORKBENCH__ && document.querySelector(".maplibregl-canvas"))');
  await new Promise(resolve => setTimeout(resolve, 800));
  await waitFor('window.__ROAD_WORKBENCH__.getMap()?.isStyleLoaded()');
  assert(await evaluate('Boolean(window.__ROAD_WORKBENCH__.getMap().getLayer("road-route-line"))'), '参考线图层缺失');
  const catalog = await invoke('facilities_catalog');
  assert.equal(catalog.entries.length, 66); check('原生设施目录', { entries: catalog.entries.length });
  await screenshot('01-workspace.png');
  const gesturePoint = await evaluate('(()=>{const b=document.querySelector(".maplibregl-canvas").getBoundingClientRect();return {x:b.x+b.width*.6,y:b.y+b.height*.55};})()');
  const viewBefore = await evaluate('({zoom:window.__ROAD_WORKBENCH__.getMap().getZoom(),center:window.__ROAD_WORKBENCH__.getMap().getCenter().toArray()})');
  await command('Input.dispatchMouseEvent', {type:'mouseWheel', ...gesturePoint, deltaX:0, deltaY:-120});
  await new Promise(resolve=>setTimeout(resolve,600));
  assert(await evaluate(`window.__ROAD_WORKBENCH__.getMap().getZoom()>${viewBefore.zoom}`));
  check('鼠标滚轮缩放',true);
  const panBefore=await evaluate('({zoom:window.__ROAD_WORKBENCH__.getMap().getZoom(),center:window.__ROAD_WORKBENCH__.getMap().getCenter().toArray()})');
  await command('Input.dispatchMouseEvent',{type:'mouseWheel',...gesturePoint,deltaX:18,deltaY:12});
  await new Promise(resolve=>setTimeout(resolve,200));
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getMap().getZoom()'),panBefore.zoom);
  assert.notDeepEqual(await evaluate('window.__ROAD_WORKBENCH__.getMap().getCenter().toArray()'),panBefore.center);
  check('触控板精细双指滚动平移',true);
  const pinchBefore=await evaluate(`(()=>{const m=window.__ROAD_WORKBENCH__.getMap(),b=m.getCanvas().getBoundingClientRect();return {zoom:m.getZoom(),anchor:m.unproject([${gesturePoint.x}-b.left,${gesturePoint.y}-b.top]).toArray()};})()`);
  await command('Input.dispatchMouseEvent',{type:'mouseWheel',...gesturePoint,deltaX:0,deltaY:-15,modifiers:2});
  await new Promise(resolve=>setTimeout(resolve,200));
  assert(await evaluate(`window.__ROAD_WORKBENCH__.getMap().getZoom()>${pinchBefore.zoom}`));
  const anchorAfter=await evaluate(`(()=>{const m=window.__ROAD_WORKBENCH__.getMap(),b=m.getCanvas().getBoundingClientRect();return m.unproject([${gesturePoint.x}-b.left,${gesturePoint.y}-b.top]).toArray();})()`);
  assert(Math.abs(anchorAfter[0]-pinchBefore.anchor[0])<1e-7&&Math.abs(anchorAfter[1]-pinchBefore.anchor[1])<1e-7);
  check('触控板捏合缩放保持指针位置',true);
  await click('[aria-label="编辑路线顶点"]');
  await waitFor('window.__ROAD_WORKBENCH__.getMap().querySourceFeatures("road-route-vertices").some(f=>f.geometry.type==="Point")');
  const vertexBefore=await evaluate('window.__ROAD_WORKBENCH__.getProject().route_points.length');
  const vertexPoint=await evaluate('(()=>{const m=window.__ROAD_WORKBENCH__.getMap(),f=m.querySourceFeatures("road-route-vertices");const p=m.project(f.find(f=>f.geometry.type==="Point").geometry.coordinates);const b=m.getCanvas().getBoundingClientRect();return {x:p.x+b.left,y:p.y+b.top};})()');
  await command('Input.dispatchMouseEvent',{type:'mousePressed',...vertexPoint,button:'left',clickCount:1});
  await command('Input.dispatchMouseEvent',{type:'mouseReleased',...vertexPoint,button:'left',clickCount:1});
  await waitFor(`!document.querySelector('[aria-label="删除选中控制点"]').disabled`);
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().route_points.length'),vertexBefore);
  await click('[aria-label="删除选中控制点"]');
  await waitFor(`window.__ROAD_WORKBENCH__.getProject().route_points.length===${vertexBefore-1}`);
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'z',code:'KeyZ',modifiers:2});
  await command('Input.dispatchKeyEvent',{type:'keyUp',key:'z',code:'KeyZ',modifiers:2});
  await waitFor(`window.__ROAD_WORKBENCH__.getProject().route_points.length===${vertexBefore}`);
  check('顶点单击只选择、显式删除及撤销',true);
  await click('[aria-label="选择与平移"]');
  const dragBefore=await evaluate('window.__ROAD_WORKBENCH__.getMap().getCenter().toArray()');
  await command('Input.dispatchMouseEvent',{type:'mousePressed',...gesturePoint,button:'left',clickCount:1});
  await command('Input.dispatchMouseEvent',{type:'mouseMoved',x:gesturePoint.x+45,y:gesturePoint.y+25,button:'left',buttons:1});
  await command('Input.dispatchMouseEvent',{type:'mouseReleased',x:gesturePoint.x+45,y:gesturePoint.y+25,button:'left',clickCount:1});
  await new Promise(resolve=>setTimeout(resolve,400));
  assert.notDeepEqual(await evaluate('window.__ROAD_WORKBENCH__.getMap().getCenter().toArray()'),dragBefore);
  check('鼠标拖动平移',true);
  await click('[aria-label="绘制路线"]');
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getMap().doubleClickZoom.isEnabled()'),false);
  const doubleBefore=await evaluate('({n:window.__ROAD_WORKBENCH__.getProject().route_points.length,z:window.__ROAD_WORKBENCH__.getMap().getZoom()})');
  for(const clickCount of [1,2]) {
    await command('Input.dispatchMouseEvent',{type:'mousePressed',...gesturePoint,button:'left',clickCount});
    await command('Input.dispatchMouseEvent',{type:'mouseReleased',...gesturePoint,button:'left',clickCount});
  }
  await new Promise(resolve=>setTimeout(resolve,200));
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getMap().getZoom()'),doubleBefore.z);
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().route_points.length'),doubleBefore.n+1);
  await click('[aria-label="撤销上一步"]');
  await click('[aria-label="选择与平移"]');
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getMap().doubleClickZoom.isEnabled()'),true);
  check('绘制双击不缩放且不重复添加顶点',true);
  await click('[aria-label="选择地图底图"]');
  const popupZoom=await evaluate('window.__ROAD_WORKBENCH__.getMap().getZoom()');
  const popupPoint=await evaluate('(()=>{const b=document.querySelector(".basemap-picker").getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};})()');
  await command('Input.dispatchMouseEvent',{type:'mouseWheel',...popupPoint,deltaX:0,deltaY:120});
  await new Promise(resolve=>setTimeout(resolve,250));
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getMap().getZoom()'),popupZoom);
  await click('[aria-label="关闭底图选择器"]');
  check('底图浮层滚动不缩放地图',true);


  await clickText('生成道路');
  await waitFor('document.body.innerText.includes("道路几何生成完成")');
  const projectFile = path.join(outputDirectory, 'native-project.json');
  await queueDialog('save', projectFile); await click('[aria-label="保存项目"]');
  await waitFor('document.body.innerText.includes("项目已保存")');
  const project = JSON.parse(await fs.readFile(projectFile, 'utf8'));
  assert.equal(project.output.response.projected_crs, 'EPSG:32650');
  assert.equal(project.output.response.paved_width_m, 20);
  assert.equal(project.output.input_version, project.input_version);
  assert(project.output.response.feature_count > 0); check('UI 调用实际 Rust 引擎并保存', { feature_count: project.output.response.feature_count, width_m: 20 });
  await screenshot('02-generated-road.png');
  await click('[aria-label="道路"]'); await click('#road-tab-display');
  const unchangedOutput=await evaluate('JSON.stringify(window.__ROAD_WORKBENCH__.getProject().output)');
  const unchangedVersion=await evaluate('window.__ROAD_WORKBENCH__.getProject().input_version');
  for(const surface of ['concrete','gravel','asphalt']) {
    await evaluate(`(()=>{const e=document.querySelector('#surface-type');e.value=${JSON.stringify(surface)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
    await waitFor(`window.__ROAD_WORKBENCH__.getMap().getStyle().layers.some(l=>l.id.endsWith('-texture')&&l.paint['fill-pattern']==='pavement-${surface}')`);
    assert.equal(await evaluate('JSON.stringify(window.__ROAD_WORKBENCH__.getProject().output)'),unchangedOutput);
    assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().input_version'),unchangedVersion);
  }
  for(const mode of ['components','realistic']) {
    await evaluate(`(()=>{const e=document.querySelector('#render-mode');e.value=${JSON.stringify(mode)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
    await waitFor(`window.__ROAD_WORKBENCH__.getMap().getStyle().layers.filter(l=>l.id.endsWith('-texture')).every(l=>l.layout.visibility===${JSON.stringify(mode==='components'?'none':'visible')})`);
    assert.equal(await evaluate('JSON.stringify(window.__ROAD_WORKBENCH__.getProject().output)'),unchangedOutput);
    assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().input_version'),unchangedVersion);
  }
  assert(await evaluate('document.querySelector(".panel-heading").getBoundingClientRect().height<=36'));
  await screenshot('24-live-pavement-display.png');
  check('材质与成果表达即时切换保留生成结果及紧凑标题栏',true);

  const imported = await invoke('import_vector', { path: path.join(workspace, 'fixtures/sample-route.geojson') });
  assert.equal(imported.collection.features.length, 1); assert.equal(imported.source_crs, 'EPSG:4326'); check('原生矢量导入', { source_crs: imported.source_crs });

  const canceled = await evaluate(`(async()=>{const p=window.__ROAD_WORKBENCH__.getProject();const jobId='qa-cancel-'+Date.now();const result=window.__TAURI_INTERNALS__.invoke('generate_road',{jobId,request:{points:Array.from({length:20000},(_,i)=>[448000+i,4419000+Math.sin(i/100)*10]),crs:p.crs,section:p.section}}).then(()=>({completed:true}),error=>({error:String(error)}));let accepted=false;for(let i=0;i<100&&!accepted;i++){accepted=await window.__TAURI_INTERNALS__.invoke('cancel_generation',{jobId});if(!accepted)await new Promise(r=>setTimeout(r,5));}return {accepted,...await result};})()`);
  assert.equal(canceled.accepted,true);assert(canceled.error?.includes('取消'),JSON.stringify(canceled));
  check('实际后台引擎任务取消',canceled);
  const crs = await invoke('crs_definition', { crs: 'EPSG:32650' }); assert(crs.includes('+proj=utm')); check('PROJ 定义', crs);
  await click('[aria-label="设施"]');
  await waitFor('document.querySelectorAll(".template-card").length > 0');
  await click('.template-place');
  const canvas = await evaluate('(()=>{const b=document.querySelector(".maplibregl-canvas").getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};})()');
  await command('Input.dispatchMouseEvent', { type: 'mousePressed', x: canvas.x, y: canvas.y, button: 'left', clickCount: 1 });
  await command('Input.dispatchMouseEvent', { type: 'mouseReleased', x: canvas.x, y: canvas.y, button: 'left', clickCount: 1 });
  await waitFor('document.body.innerText.includes("设施已放置")');
  await waitFor('document.querySelector(".save-badge").innerText === "未保存"');
  const originalX=await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].x');
  await evaluate(`(()=>{const e=document.querySelector('[aria-label="坐标 X"]');e.focus();e.blur();})()`);
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].x'),originalX); check('坐标展示不截断原始精度',true);
  await evaluate(`(()=>{const e=document.querySelector('[aria-label="坐标 X"]');e.focus();Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,"");e.dispatchEvent(new Event("input",{bubbles:true}));e.blur();})()`);
  await waitFor(`document.querySelector('[aria-label="坐标 X"]').getAttribute("aria-invalid") === "true"`);
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].x'),originalX);
  await evaluate(`document.querySelector('[aria-label="坐标 X"]').focus()`);
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});
  await waitFor(`document.querySelector('[aria-label="坐标 X"]').getAttribute("aria-invalid") === "false"`); check('空值就地校验与 Esc 取消草稿',true);
  await evaluate(`(()=>{const e=document.querySelector('[aria-label="标志编码"]');e.focus();Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,"001");e.dispatchEvent(new Event("input",{bubbles:true}));e.blur();})()`);
  await waitFor('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].template.specification.sign_code === "001"'); check('设施编码保留前导零',true);
  await click('[aria-label="撤销上一步"]'); assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].template.specification.sign_code'), '');
  await click('[aria-label="重做上一步"]'); assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].template.specification.sign_code'), '001'); check('实例编辑撤销重做保留道路成果',true);
  const draftX = await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].x + 0.25');
  await evaluate(`(()=>{const e=document.querySelector('[aria-label="坐标 X"]');e.focus();Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,${JSON.stringify(draftX)});e.dispatchEvent(new Event("input",{bubbles:true}));})()`);
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'s',code:'KeyS',modifiers:2});
  await waitFor('document.querySelector(".save-badge").innerText === "已保存"'); check('Ctrl+S 保存与独立保存状态',true);
  await new Promise(resolve => setTimeout(resolve, 300));
  const facilityProject = JSON.parse(await fs.readFile(projectFile, 'utf8'));
  assert.equal(facilityProject.manual_facilities[0].x,draftX); check('Ctrl+S 提交当前数值草稿后保存',true);
  assert.equal(facilityProject.manual_facilities.length, 1); assert.equal(facilityProject.manual_facilities[0].confirmed, false);
  assert(facilityProject.output, '设施编辑不应清除道路成果');
  assert(facilityProject.manual_facilities[0].template.id); check('地图放置设施及快照保存', facilityProject.manual_facilities[0].template.id);
  await screenshot('03-facility.png');
  const raster = await invoke('import_raster', { path: path.join(workspace, 'artifacts/fixtures/test-basemap.tif') });
  assert(raster.bounds.every(Number.isFinite));
  const lon = (raster.bounds[0] + raster.bounds[2]) / 2, lat = (raster.bounds[1] + raster.bounds[3]) / 2;
  const z = 16, size = 2 ** z, x = Math.floor((lon + 180) / 360 * size), y = Math.floor((1 - Math.asinh(Math.tan(lat * Math.PI / 180)) / Math.PI) / 2 * size);
  const png = await evaluate(`window.__TAURI_INTERNALS__.invoke('raster_tile',${JSON.stringify({ id: raster.id, z, x, y })}).then(value=>Array.from(new Uint8Array(value)).slice(0,8))`);
  assert.deepEqual(png, [137, 80, 78, 71, 13, 10, 26, 10]); check('分块影像瓦片', { bounds: raster.bounds, z, x, y });
  const validity = await invoke('validate_geometry', { crs: project.crs, collection: { type: 'FeatureCollection', features: [{ type: 'Feature', properties: {}, geometry: { type: 'Polygon', coordinates: [[[0, 0], [1, 1], [1, 0], [0, 1], [0, 0]]] } }] } });
  assert.equal(validity.valid, false); assert(validity.invalid_features[0].reason.includes('Self-intersection')); check('GEOS 定位区域自交', validity.invalid_features);
  await click('[aria-label="图层"]'); await queueDialog('open', path.join(workspace, 'artifacts/fixtures/test-basemap.tif')); await clickText('添加本地栅格');
  await waitFor('document.body.innerText.includes("已载入栅格")');
  await waitFor('window.__ROAD_WORKBENCH__.getMap().areTilesLoaded()', 60);
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().rasters.length'), 1); check('UI 本地影像视口加载', true);
  await screenshot('04-raster-workspace.png');
  const uiGpkgFile = path.join(outputDirectory, 'ui-all-layers.gpkg');
  await queueDialog('save', uiGpkgFile); await click('[aria-label="导出GeoPackage"]');
  await waitFor('document.body.innerText.includes("GeoPackage 已导出")'); assert((await fs.stat(uiGpkgFile)).size > 1000); check('UI 组合图层导出 GeoPackage', uiGpkgFile);
  const uiGeojsonFile = path.join(outputDirectory, 'ui-all-layers.geojson');
  await queueDialog('save', uiGeojsonFile); await click('[aria-label="导出WGS84 GeoJSON"]');
  await waitFor('document.body.innerText.includes("WGS84 GeoJSON 已导出")');
  const uiCollection = JSON.parse(await fs.readFile(uiGeojsonFile, 'utf8')); assert.equal(uiCollection.features.length, project.output.response.feature_count + 2); check('UI 道路与人工设施 WGS84 导出', uiCollection.features.length);
  const gpkgFile = path.join(outputDirectory, 'native-export.gpkg');
  const exported = await invoke('export_geopackage', { path: gpkgFile, layers: [{ name: 'roads', crs: project.crs, collection: project.output.response.feature_collection }] });
  assert.equal(exported.layer_count, 1); assert((await fs.stat(gpkgFile)).size > 1000); check('原生工程 CRS GeoPackage 导出', gpkgFile);
  const geojsonFile = path.join(outputDirectory, 'native-export.geojson');
  await invoke('write_geojson', { path: geojsonFile, collection: imported.collection });
  const standard = JSON.parse(await fs.readFile(geojsonFile, 'utf8')); assert(!standard.crs); check('WGS84 GeoJSON 导出', geojsonFile);
  let rejected = false;
  try { await invoke('write_geojson', { path: path.join(outputDirectory, 'invalid-projected.geojson'), collection: project.output.response.feature_collection }); } catch { rejected = true; }
  assert(rejected); check('拒绝将投影坐标冒充地理 GeoJSON', true);
  const legacy = structuredClone(facilityProject); legacy.schema_version = 1; delete legacy.input_version; delete legacy.view; delete legacy.output; delete legacy.catalog;
  legacy.scene_options = { enabled: ['lighting'], legacy_marker: '保留未迁移规则' }; delete legacy.manual_facilities[0].template; legacy.manual_facilities[0].kind = 'sign';
  const legacyFile = path.join(outputDirectory, 'legacy-project.json'); await fs.writeFile(legacyFile, JSON.stringify(legacy));
  await queueDialog('open', legacyFile); await click('[aria-label="打开项目"]');
  await waitFor('Boolean(document.querySelector(".workbench-dialog"))');
  await clickText('取消'); assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().rasters.length'),1);
  await click('[aria-label="打开项目"]'); await waitFor('Boolean(document.querySelector(".workbench-dialog"))'); await clickText('保存并继续');
  await waitFor('document.body.innerText.includes("已从 schema 1 迁移")'); check('打开项目的取消与保存保护',true);
  await waitFor('!window.__ROAD_WORKBENCH__.getMap().getStyle().layers.some(layer => layer.id.startsWith("raster-"))');
  check('切换项目清除旧影像图层', true);
  await click('[aria-label="保存项目"]'); await new Promise(resolve => setTimeout(resolve, 300));
  const migrated = JSON.parse(await fs.readFile(legacyFile, 'utf8'));
  assert.equal(migrated.schema_version, 2); assert.equal(migrated.manual_facilities.length, 1); assert(migrated.manual_facilities[0].template);
  assert.equal(migrated.catalog.entries.length, 66, '旧项目恢复后应保留完整系统目录');
  assert.deepEqual(migrated.scene_options, legacy.scene_options); check('schema1 项目与无模板旧设施迁移', migrated.manual_facilities[0].kind);
  await click('[aria-label="倾斜视角示意（无高程）"]'); await new Promise(resolve => setTimeout(resolve, 600));
  await screenshot('05-tilted-view.png');
  await click('[aria-label="倾斜视角示意（无高程）"]');
  await clickText('生成道路'); await waitFor('Boolean(window.__ROAD_WORKBENCH__.getProject().output)');
  const count = await evaluate('window.__ROAD_WORKBENCH__.getProject().route_points.length');
  await click('[aria-label="绘制路线"]');
  await command('Input.dispatchMouseEvent', { type: 'mousePressed', x: canvas.x - 35, y: canvas.y - 60, button: 'left', clickCount: 1 });
  await command('Input.dispatchMouseEvent', { type: 'mouseReleased', x: canvas.x - 35, y: canvas.y - 60, button: 'left', clickCount: 1 });
  await waitFor(`window.__ROAD_WORKBENCH__.getProject().route_points.length === ${count + 1}`);
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().output'), null);
  await waitFor('!window.__ROAD_WORKBENCH__.getMap().getStyle().layers.some(layer=>layer.id.startsWith("output-"))'); check('路线编辑清除过期道路成果', true);
  await click('[aria-label="撤销上一步"]'); assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().route_points.length'), count);
  await click('[aria-label="重做上一步"]'); assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().route_points.length'),count+1);
  await click('[aria-label="撤销上一步"]');
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});
  await waitFor(`document.querySelector('[aria-label="选择与平移"]').classList.contains("selected")`); check('路线重做与 Esc 退出绘制',true);
  await click('[aria-label="道路"]'); await screenshot('07-cross-section.png');
  await click('.cross-section__copy-options > summary');
  await clickText('左复制到右');
  await click('.cross-section__copy-options > summary');
  const diagramProject = await evaluate('window.__ROAD_WORKBENCH__.getProject()');
  const blankSide = {left_emergency_width:0,right_emergency_width:0,left_shoulder_width:0,right_shoulder_width:0,left_slope_width:0,right_slope_width:0,median_width:0};
  for (const [name,left,right,median] of [['仅左侧',[3.5,3.5,3.5,3.5],[],0],['仅右侧',[],[3.5,3.5,3.5,3.5],0],['极端不对称',[200,200],[0.1],1],['宽隔离带',[3.5],[3.5],200]]) {
    await evaluate(`window.__ROAD_WORKBENCH__.loadProject(${JSON.stringify({...diagramProject,section:{...diagramProject.section,...blankSide,left_lanes:left,right_lanes:right,median_width:median}})})`);
    const leftWidth=left.reduce((sum,w)=>sum+w,0),rightWidth=right.reduce((sum,w)=>sum+w,0);
    const expectedReference=500+(leftWidth-rightWidth)*Math.min(34,850/Math.max(leftWidth+rightWidth+median,1))/2;
    await waitFor(`Math.abs(Number(document.querySelector(".cross-section__reference").getAttribute("x1"))-${expectedReference})<0.001`);
    assert(await evaluate('[...document.querySelectorAll(".cross-section__diagram rect")].every(e=>Number(e.getAttribute("x"))>=74 && Number(e.getAttribute("x"))+Number(e.getAttribute("width"))<=926)'), name+'横断面越界');
    if(name==='仅左侧') await screenshot('22-one-sided-section.png');
  }
  await evaluate(`window.__ROAD_WORKBENCH__.loadProject(${JSON.stringify(diagramProject)})`);
  await click('#road-tab-display');
  assert(await evaluate('!document.querySelector("#road-page-display").hidden && document.querySelector("#road-page-section").hidden'));
  await click('#road-tab-along');
  assert(await evaluate('!document.querySelector("#road-page-along").hidden && document.querySelector("#road-page-section").hidden'));
  await screenshot('23-along-route-tab.png');
  await click('#road-tab-section');
  check('单侧与极端不对称横断面完整显示、道路分类页签切换',true);
  await click('.cross-section__sync-control input');
  await evaluate(`(()=>{const e=document.querySelector('[aria-label="左侧第 1 条车道宽度"]');e.focus();Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,"3.7");e.dispatchEvent(new Event("input",{bubbles:true}));e.blur();})()`);
  await waitFor('window.__ROAD_WORKBENCH__.getProject().section.left_lanes[0] === 3.7');
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().section.right_lanes[0]'),3.7); check('左右同步和数值完成编辑提交',true);
  await click('[aria-label="撤销上一步"]');
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().section.left_lanes[0]'),3.5);
  await screenshot('07-cross-section.png');
  assert.deepEqual(await evaluate('window.__ROAD_WORKBENCH__.getProject().section.left_lanes'),await evaluate('window.__ROAD_WORKBENCH__.getProject().section.right_lanes')); check('横断面分组与明确复制方向',true);
  await click('[aria-label="切换路线摘要"]'); await waitFor('document.querySelector(".route-card-stats") !== null');
  await click('[aria-label="切换图例"]'); await waitFor('document.querySelector(".legend-title").getAttribute("aria-expanded") === "true"');
  await click('[aria-label="切换路线摘要"]'); await click('[aria-label="切换图例"]'); check('图例与路线摘要真实折叠',true);
  await click('[aria-label="折叠工具面板"]'); await waitFor('getComputedStyle(document.querySelector(".side-panel")).display === "none"');
  await click('[aria-label="展开工具面板"]'); await waitFor('getComputedStyle(document.querySelector(".side-panel")).display !== "none"'); check('工具面板折叠与恢复',true);
  await click('[aria-label="折叠检查器"]'); await waitFor('getComputedStyle(document.querySelector(".inspector")).display === "none"');
  await click('[aria-label="切换属性面板"]'); await waitFor('getComputedStyle(document.querySelector(".inspector")).display !== "none"'); check('属性面板折叠与恢复', true);
  await command('Emulation.setDeviceMetricsOverride', { width: 1024, height: 720, deviceScaleFactor: 1, mobile: false });
  await new Promise(resolve => setTimeout(resolve, 500));
  assert(await evaluate('document.documentElement.scrollWidth <= innerWidth'), '小窗口出现横向溢出');
  assert(await evaluate('document.querySelector(".map-statusbar").getBoundingClientRect().bottom <= innerHeight + 1'), '状态栏被裁剪');
  assert(await evaluate(`(()=>{const name=document.querySelector('.project-title > span:nth-child(2)');const old=name.textContent;name.textContent='复杂交叉口道路改造工程-横断面与沿线设施设计项目.json';const menu=document.querySelector('.workbench-menubar').getBoundingClientRect();const project=document.querySelector('.project-title').getBoundingClientRect();const actions=document.querySelector('.top-actions').getBoundingClientRect();const save=document.querySelector('.top-actions [aria-label="保存项目"]').getBoundingClientRect();const valid=menu.right<=project.left&&project.right<=actions.left&&save.right<=innerWidth;name.textContent=old;return valid;})()`), '长项目名挤压菜单或保存按钮');
  await click('.command-menu > button');
  assert(await evaluate(`(()=>{const popup=document.querySelector('.command-popup');const first=popup.querySelector('button:not(:disabled)');const r=first.getBoundingClientRect();const hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return first.contains(hit)&&popup.getBoundingClientRect().right<=innerWidth;})()`), '下拉菜单被工具栏遮挡或超出窗口');
  await screenshot('13-compact-header-menu.png');
  await click('.command-menu > button');
  check('紧凑工作栏长项目名与下拉菜单可访问性', true);
  assert(await evaluate('(()=>{const bar=document.querySelector(".map-statusbar").getBoundingClientRect();const coord=document.querySelector(".map-coordinate").getBoundingClientRect();const status=document.querySelector(".map-status").getBoundingClientRect();return bar.height<=34&&Math.abs((coord.top+coord.bottom)/2-(status.top+status.bottom)/2)<2;})()'), '坐标与反馈未合并为单行');
  check('单行坐标与操作状态栏',true);
  await screenshot('06-1024x720.png'); check('1024×720 工作区与状态栏布局', true);
  assert(await evaluate('getComputedStyle(document.querySelector(".inspector")).display === "none"'));
  check('窄窗口收起工程属性并扩展主地图',true);
  await click('[aria-label="切换属性面板"]');
  await click('[aria-label="折叠工具面板"]');
  await click('[aria-label="专注地图"]');
  await waitFor('getComputedStyle(document.querySelector(".side-panel")).display === "none" && getComputedStyle(document.querySelector(".inspector")).display === "none"');
  await waitFor('Math.abs(document.querySelector(".maplibregl-canvas").getBoundingClientRect().width-document.querySelector(".map-workspace").clientWidth)<2');
  await screenshot('14-focus-map.png');
  await click('[aria-label="恢复面板布局"]');
  await waitFor('getComputedStyle(document.querySelector(".side-panel")).display === "none" && getComputedStyle(document.querySelector(".inspector")).display !== "none"');
  await click('[aria-label="展开工具面板"]'); check('专注地图与原有面板组合恢复',true);
  await click('[aria-label="绘制路线"]');
  await click('[aria-label="切换路线摘要"]'); await click('[aria-label="切换图例"]');
  assert(await evaluate(`(()=>{const hint=document.querySelector('.drawing-hint').getBoundingClientRect();const route=document.querySelector('.route-map-card').getBoundingClientRect();const legend=document.querySelector('.legend-card').getBoundingClientRect();const tools=document.querySelector('.map-top-controls').getBoundingClientRect();return hint.top>=Math.max(route.bottom,legend.bottom)&&route.top>=tools.bottom&&route.right<=legend.left;})()`), '绘制提示、路线摘要或图例互相遮挡');
  await screenshot('15-drawing-overlays.png');check('窄画布绘制提示与展开摘要图例无重叠',true);
  const menuPoint = await evaluate('(()=>{const r=document.querySelector(".map-workspace").getBoundingClientRect();const footer=document.querySelector(".map-statusbar").getBoundingClientRect();return {x:r.right-10,y:footer.top-3};})()');
  await command('Input.dispatchMouseEvent',{type:'mousePressed',...menuPoint,button:'right',clickCount:1});
  await command('Input.dispatchMouseEvent',{type:'mouseReleased',...menuPoint,button:'right',clickCount:1});
  await waitFor('Boolean(document.querySelector(".map-context"))');
  assert(await evaluate(`(()=>{const menu=document.querySelector('.map-context');const r=menu.getBoundingClientRect();const map=document.querySelector('.map-workspace').getBoundingClientRect();const footer=document.querySelector('.map-statusbar').getBoundingClientRect();return r.right<=map.right&&r.bottom<=footer.top&&!menu.innerText.includes('完成区域设施')&&menu.innerText.includes('完成路线绘制');})()`), '右键菜单被裁切或命令与当前工具不符');
  await screenshot('16-map-context.png');
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});
  await waitFor('!document.querySelector(".map-context")');
  assert(await evaluate('Boolean(document.querySelector(".drawing-hint"))'), '关闭右键菜单意外退出绘制');check('右键菜单边缘避让与独立Escape关闭',true);
  await click('[aria-label="选择地图底图"]');
  await waitFor('Boolean(document.querySelector(".basemap-picker"))');
  assert(await evaluate(`(()=>{const picker=document.querySelector('.basemap-picker').getBoundingClientRect();const anchor=document.querySelector('.basemap-chip').getBoundingClientRect();const map=document.querySelector('.map-workspace').getBoundingClientRect();return Math.abs(picker.left-anchor.left)<2&&picker.bottom<=anchor.top&&picker.right<=map.right;})()`), '底图弹出层未与按钮关联或超出窄画布');
  await screenshot('17-anchored-basemap.png');
  const pickerStatus=await evaluate('document.querySelector(".status-message").textContent');
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});
  await waitFor('!document.querySelector(".basemap-picker")');
  assert(await evaluate('Boolean(document.querySelector(".drawing-hint"))'), '底图关闭意外退出绘制');
  assert.equal(await evaluate('document.querySelector(".status-message").textContent'),pickerStatus);check('底图锚定布局与关闭时保留绘制状态',true);
  await click('[aria-label="选择与平移"]');
  await click('[aria-label="切换路线摘要"]'); await click('[aria-label="切换图例"]');
  await click('[aria-label="调整左侧面板宽度"]');
  await evaluate(`document.querySelector('[aria-label="调整左侧面板宽度"]').focus()`);
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight'});
  await waitFor('JSON.parse(localStorage.getItem("road-workbench-layout")).left === 316'); check('面板宽度调整与持久化',true);
  await click('[aria-label="设施"]');
  assert.equal(await evaluate('document.querySelector("#facility-category").options.length'),13);
  const instanceBeforeTemplateEdit = await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].template');
  await evaluate('document.querySelector(".template-menu").open=true');
  await clickText('编辑模板'); await waitFor('Boolean(document.querySelector(".workbench-dialog"))');
  assert.equal(await evaluate('document.querySelectorAll(".template-menu[open]").length'),0);
  assert(await evaluate('document.activeElement.matches(".workbench-dialog input")'), '编辑弹窗未聚焦可编辑字段');
  await evaluate(`(()=>{const e=document.querySelector('.workbench-dialog [aria-label="标志编码"]');e.focus();Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,"009");e.dispatchEvent(new Event("input",{bubbles:true}));e.blur();})()`);
  await clickText('保存模板'); await waitFor('!document.querySelector(".workbench-dialog")');
  assert.deepEqual(await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities[0].template'), instanceBeforeTemplateEdit); check('模板编辑不覆盖已放置实例与完整分类入口',true);
  await clickText('新建'); await waitFor('Boolean(document.querySelector("#template-name"))');
  assert.equal(await evaluate('document.activeElement.id'),'template-name');
  await evaluate(`document.querySelector('.workbench-dialog [aria-label="关闭对话框"]').focus()`);
  await command('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',modifiers:8});
  assert(await evaluate('Boolean(document.activeElement.closest(".workbench-dialog"))'), '反向Tab逸出模态窗口');
  await screenshot('18-template-modal.png');check('弹窗字段聚焦、菜单收起与键盘焦点约束',true);
  await evaluate('(()=>{const e=document.querySelector("#template-name");Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,"用户模板验证");e.dispatchEvent(new Event("input",{bubbles:true}));})()');
  await clickText('创建模板'); await waitFor('document.querySelector(".workbench-dialog").innerText.includes("用户模板验证")');
  await clickText('保存模板'); await waitFor('document.querySelector(".catalog-count").innerText.includes("67")'); check('原生风格模板创建与编辑表单',true);
  await screenshot('08-template-library.png');
  await click('[aria-label="数据"]');
  await evaluate('window.__ROAD_WORKBENCH__.requestClose()');
  await waitFor('Boolean(document.querySelector(".workbench-dialog"))');
  await clickText('取消'); await waitFor('!document.querySelector(".workbench-dialog")'); check('原生窗口关闭保护',true);
  assert.equal(await evaluate('document.querySelectorAll(".workbench-menubar > .command-menu").length'),6); check('原版六组标准菜单恢复',true);
  await clickText('数据'); await clickText('连接远程数据…');
  await waitFor('document.querySelector(".source-tools") !== null');
  assert(await evaluate('document.querySelector(".source-tools").parentElement.open')); check('WFS 与 PostGIS 数据连接入口',true);
  await clickText('数据'); await clickText('配置字段映射…');
  await waitFor('document.querySelector(".field-mapping") !== null'); check('完整路线与横断面字段映射入口',true);
  assert(await evaluate('!document.querySelector(".project-details").open'), '项目详情应默认折叠');
  assert.equal(await evaluate('document.querySelectorAll(".data-panel > .section-block:not(.project-details) button").length'),3);
  await click('.project-details > summary');
  assert(await evaluate('document.querySelector(".project-details").innerText.includes("输入版本")'), '项目详情缺少原有元数据');
  await click('.project-details > summary');
  await click('[aria-label="切换坐标显示"]');
  assert(await evaluate('document.querySelector(".coordinate-system").innerText.includes("工程 XY")'));
  await click('[aria-label="切换坐标显示"]');
  assert(await evaluate('document.querySelector(".coordinate-system").innerText.includes("WGS84")'));
  check('数据面板去重、项目详情折叠与坐标显示切换',true);
  await click('[aria-label="选择地图底图"]');
  assert.equal(await evaluate('document.querySelectorAll(".basemap-picker__option").length'),8);
  assert(await evaluate('document.querySelector(".basemap-picker").getBoundingClientRect().height <= 400'), '底图目录占位过大');
  assert(await evaluate('!document.querySelector(".basemap-picker input[type=password]")'), '底图令牌应按需展开');
  await evaluate('[...document.querySelectorAll(".basemap-picker__option")].find(e=>e.innerText.includes("令牌")).click()');
  await waitFor('Boolean(document.querySelector(".basemap-picker input[type=password]"))');
  assert(await evaluate('document.querySelector(".basemap-picker__error").innerText.includes("令牌")'), '缺令牌时应显示可操作的提示');
  check('紧凑底图目录与凭据按需展开',true);
  await screenshot('09-basemap-picker.png'); check('八种在线底图与XYZ/WMS选择入口',true);
  await evaluate('document.querySelector(".basemap-picker__local").click()');
  await waitFor('!document.querySelector(".basemap-picker")'); assert.equal(await evaluate('Boolean(window.__ROAD_WORKBENCH__.getMap().getSource("user-xyz"))'),false); check('无在线底图切换与清理',true);
  await clickText('视图'); await clickText('对比原始底图');
  await waitFor('Boolean(document.querySelector(".compare-banner"))');
  await click('.compare-banner'); await waitFor('!document.querySelector(".compare-banner")'); check('原始底图对比与恢复',true);
  await click('[aria-label="道路"]');
  const manualBeforeAuto=await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities.length');
  await evaluate('(()=>{const label=[...document.querySelectorAll(".along-route-kinds label")].find(e=>e.innerText.includes("护栏"));label.querySelector("input").click();})()');
  await click('#road-tab-along');
  await clickText('应用沿线布设');
  await waitFor('window.__ROAD_WORKBENCH__.getProject().output?.response?.ancillary_layers?.length > 0');
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().manual_facilities.length'),manualBeforeAuto); check('沿线自动设施与手动实例隔离',true);
  const autoGeojson=path.join(outputDirectory,'automatic-facilities.geojson');
  await queueDialog('save',autoGeojson); await clickText('文件'); await clickText('导出 GeoJSON（WGS84）…');
  await waitFor('document.body.innerText.includes("WGS84 GeoJSON 已导出")');
  const autoFeatures=JSON.parse(await fs.readFile(autoGeojson,'utf8')).features.filter(feature=>feature.properties?.source==='parameter_template');
  assert(autoFeatures.length>0 && autoFeatures.every(feature=>feature.properties.confirmed===false)); check('自动设施WGS84导出保留来源与确认状态',autoFeatures.length);
  const autoGpkg=path.join(outputDirectory,'automatic-facilities.gpkg');
  await queueDialog('save',autoGpkg);await clickText('文件');await clickText('导出 GeoPackage…');await waitFor('document.body.innerText.includes("GeoPackage 已导出")');
  const autoMetadata=await invoke('list_vector_layers',{path:autoGpkg});
  assert(autoMetadata.layers.some(layer=>/护栏|照明|guardrail|lighting/.test(layer.name)));check('自动设施GeoPackage独立图层导出',autoMetadata.layers.length);
  await clickText('清除自动设施'); await waitFor('window.__ROAD_WORKBENCH__.getProject().output?.response?.ancillary_layers?.length === 0'); check('清除自动设施保留道路成果',true);
  await screenshot('10-restored-workbench.png');
  await queueDialog('open',autoGpkg);await clickText('数据');await clickText('添加矢量底图…');
  await waitFor('document.querySelector(".workbench-dialog")?.innerText.includes("选择数据图层")');
  await screenshot('12-layer-selection.png');await clickText('取消');
  await waitFor('!document.querySelector(".workbench-dialog")');check('GeoPackage多图层选择与取消保护',true);
  await clickText('编辑');await clickText('清除道路成果');
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().output'),null);
  await click('[aria-label="撤销上一步"]');assert(await evaluate('Boolean(window.__ROAD_WORKBENCH__.getProject().output)'));check('菜单清除成果可撤销恢复',true);
  const beforeMapping=await evaluate('window.__ROAD_WORKBENCH__.getProject()');
  await evaluate(`window.__ROAD_WORKBENCH__.loadProject({...window.__ROAD_WORKBENCH__.getProject(),source_mapping:{},manual_section:null,source_fields:["qa_count","qa_width","qa_bad"],mapped_attributes:{qa_count:1,qa_width:4.25,qa_bad:"not-a-number"}})`);
  await click('[aria-label="数据"]');await clickText('数据');await clickText('配置字段映射…');
  await evaluate('(()=>{const e=[...document.querySelectorAll(".field-mapping__grid label")].find(l=>l.innerText.startsWith("左侧车道数")).querySelector("select");e.value="qa_count";e.dispatchEvent(new Event("change",{bubbles:true}));})()');
  await waitFor('window.__ROAD_WORKBENCH__.getProject().section.left_lanes.length===1');
  await evaluate('(()=>{const e=[...document.querySelectorAll(".field-mapping__grid label")].find(l=>l.innerText.startsWith("左侧车道宽度")).querySelector("select");e.value="qa_width";e.dispatchEvent(new Event("change",{bubbles:true}));})()');
  await waitFor('window.__ROAD_WORKBENCH__.getProject().section.left_lanes[0]===4.25');
  await evaluate('(()=>{const e=[...document.querySelectorAll(".field-mapping__grid label")].find(l=>l.innerText.startsWith("左侧车道宽度")).querySelector("select");e.value="qa_bad";e.dispatchEvent(new Event("change",{bubbles:true}));})()');
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().section.left_lanes[0]'),4.25);check('横断面字段映射进入输入并拒绝无效数值',true);
  await evaluate(`window.__ROAD_WORKBENCH__.loadProject(${JSON.stringify(beforeMapping)})`);await click('[aria-label="道路"]');
  const beforeLegacyBackground=await evaluate('window.__ROAD_WORKBENCH__.getProject()');
  const legacyBackgroundFile=path.join(outputDirectory,'legacy-vector-background.json');
  await fs.writeFile(legacyBackgroundFile,JSON.stringify({...beforeLegacyBackground,file_basemaps:[{kind:'local-vector',path:autoGpkg,layer:'参考线'}],vector_basemaps:[]}));
  await queueDialog('open',legacyBackgroundFile);await click('[aria-label="打开项目"]');await waitFor('Boolean(document.querySelector(".workbench-dialog"))');await clickText('放弃更改');
  await waitFor('window.__ROAD_WORKBENCH__.getProject().vector_basemaps?.length===1');
  assert.equal(await evaluate('window.__ROAD_WORKBENCH__.getProject().vector_basemaps[0].layer'),'参考线');check('原版项目矢量文件底图恢复',true);
  await evaluate(`window.__ROAD_WORKBENCH__.loadProject(${JSON.stringify(beforeLegacyBackground)})`);
  await click('[aria-label="设施"]');
  const longEntry={...catalog.entries[0],id:'qa.long-form',subtype:'长规格表单验证',name:'长规格表单验证',specification:Object.fromEntries(['sign_code','panel_width_m','panel_height_m','support_type','reflective_material','color','line_width_m','dash_length_m','gap_length_m','material','protection_level','height_m','post_spacing_m','foundation','transition_type','reflective_color','mounting_type','mesh_size_m','performance_basis','mounting_height_m','power_w','arm_length_m','photometry_file','luminaire_model','signal_group','controller_scheme','device_model','field_of_view_deg','power_supply','system_id','communication_type','diameter_m','depth_m','connection_id','product_model','width_m','business_station'].map(key=>[key,/_(m|w|deg)$/.test(key)?null:'']))};
  await evaluate(`window.dispatchEvent(new CustomEvent('road-catalog-add',{detail:${JSON.stringify(longEntry)}}))`);
  await evaluate(`(()=>{const e=document.querySelector('[aria-label="搜索设施模板"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,'长规格表单验证');e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await waitFor('document.querySelectorAll(".template-menu").length===1');
  await evaluate('document.querySelector(".template-menu").open=true');await clickText('编辑模板');
  await waitFor('Boolean(document.querySelector(".workbench-dialog"))');
  const titleTop=await evaluate('document.querySelector(".dialog-title").getBoundingClientRect().top');
  await evaluate('document.querySelector(".dialog-body").scrollTop=10000');
  assert.equal(await evaluate('document.querySelector(".dialog-title").getBoundingClientRect().top'),titleTop);
  assert(await evaluate(`(()=>{const dialog=document.querySelector('.workbench-dialog').getBoundingClientRect();const footer=document.querySelector('.dialog-actions').getBoundingClientRect();const save=[...document.querySelectorAll('.dialog-actions button')].find(e=>e.textContent==='保存模板');const r=save.getBoundingClientRect();return dialog.bottom<=innerHeight&&footer.bottom<=dialog.bottom+1&&save.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})()`), '长表单标题或操作区不可访问');
  await screenshot('19-long-modal.png');check('长规格弹窗独立滚动与固定标题操作区',true);
  await click('[aria-label="关闭对话框"]');
  await evaluate(`(()=>{const e=document.querySelector('[aria-label="搜索设施模板"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,'');e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await click('[aria-label="道路"]');
  if(process.env.ROAD_QA_ONLINE === '1') {
    await command('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
    await click('[aria-label="选择地图底图"]');
    await evaluate('(()=>{const map=window.__ROAD_WORKBENCH__.getMap();window.__qaOnlineSourceReady=false;window.__qaOnlineIdle=false;const loaded=e=>{if(e.sourceId==="user-xyz"&&e.isSourceLoaded){window.__qaOnlineSourceReady=true;map.off("sourcedata",loaded);}};map.on("sourcedata",loaded);map.once("idle",()=>window.__qaOnlineIdle=true);const b=[...document.querySelectorAll(".basemap-picker__option")].find(e=>e.querySelector("strong").innerText==="高德卫星");b.click();})()');
    await waitFor('window.__qaOnlineSourceReady && window.__qaOnlineIdle && window.__ROAD_WORKBENCH__.getMap().areTilesLoaded()',60);
    assert(await evaluate('Boolean(window.__ROAD_WORKBENCH__.getMap().getSource("user-xyz"))'));
    assert(await evaluate('(()=>{const a=document.querySelector(".maplibregl-ctrl-attrib");return a.getBoundingClientRect().height>0&&a.textContent.includes("高德");})()'), '底图署名被隐藏');
    await screenshot('11-amap-satellite.png'); check('高德卫星真实联网瓦片与纠偏显示',true);
  }
  await command('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
  await click('[aria-label="数据"]');
  await evaluate('document.querySelectorAll(".data-panel details").forEach(e=>e.open=false);document.querySelector(".panel-content").scrollTop=0');
  await click('[aria-label="折叠检查器"]');
  await waitFor('getComputedStyle(document.querySelector(".inspector")).display === "none"');
  await new Promise(resolve=>setTimeout(resolve,300));
  await screenshot('20-data-workspace.png');
  await click('[aria-label="选择地图底图"]');
  await screenshot('21-compact-basemap.png');
  await click('[aria-label="关闭底图选择器"]');
  assert.equal(browserErrors.length, 0, browserErrors.join('\n'));
  await fs.writeFile(path.join(outputDirectory, 'report.json'), JSON.stringify({ passed: true, checks, browserErrors }, null, 2));
  console.log(JSON.stringify({ passed: true, checks: checks.length, outputDirectory }));
} catch (error) {
  await screenshot('failure.png').catch(() => {});
  await fs.writeFile(path.join(outputDirectory, 'report.json'), JSON.stringify({ passed: false, checks, error: String(error), browserErrors }, null, 2));
  throw error;
} finally { if(originalLayout!==undefined) await evaluate(`localStorage.${originalLayout===null?'removeItem("road-workbench-layout")':`setItem("road-workbench-layout",${JSON.stringify(originalLayout)})`}`).catch(()=>{}); socket.close(); }
